version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8080"
    networks:
      - rproxy

networks:
  rproxy:
    external: true